# Generated by Django 5.2.6 on 2025-09-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familya', models.CharField(blank=True, max_length=100, null=True)),
                ('yosh', models.IntegerField()),
                ('tugilgan_sana', models.DateField()),
                ('manzil', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tajriba', models.TextField()),
                ('loyihalar', models.TextField()),
                ('qoshimcha', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
